### ISSUE TITLE
Add better icon support (dark mode)

### ISSUE THREAD

**Issue by coolcut** [puresick/redirector#1]
Based on my current setup (I use macOS in dark mode) the default icon is barely visible inside the firefox add-on menu.

<img width="243" alt="Screenshot 2020-03-18 at 09 17 33" src="https://user-images.githubusercontent.com/1376207/76943153-2e3e3780-68ff-11ea-8c99-7b3a93603d84.png">

**Comment by puresick** [comment]
I added support for system-wide dark mode and for custom light and dark themes (see [this commit](https://github.com/puresick/redirector/commit/8a5166c36768be8ef9ce76b221b4e1364645cdad)).

One thing still not working:
Automatically updating the icon color after the system-wide dark-mode is being enabled or disabled.
There is no event I can listen to which tells me about this change. The icon will update after a browser restart or after interaction with the toolbar icon.
I will revisit this issue once there will be a possibility to react it.
