### ISSUE TITLE
Add better explanation for states

### ISSUE THREAD

**Issue by coolcut** [puresick/redirector#2]
Currently, there are two different states (on/off) for this plugin. The icon appears to react upon the change of this state, but there is no explanation in what state I'm currently in other than a color change (gray/red).

Please add a more robust way of noticing in which state I'm currently in.

Possible suggestion from Grammarly: 
<img width="57" alt="Screenshot 2020-03-18 at 09 19 33" src="https://user-images.githubusercontent.com/1376207/76943473-b3c1e780-68ff-11ea-8b37-8689ef80fa51.png">

**Comment by puresick** [comment]
Added new icon for the "disabled"-state in [this commit](https://github.com/puresick/redirector/commit/8a5166c36768be8ef9ce76b221b4e1364645cdad)
