### ISSUE TITLE
Add way of "sending" a YouTube video directly to invidio.us

### ISSUE THREAD

**Issue by coolcut** [puresick/redirector#3]
When I'm currently on YouTube, I want to have a way to send this video I'm currently seeing to invidio.us without copy and pasting the URL in another tab to trigger the action. Ideally, a shortcut or a right-click menu action.

**Comment by puresick** [comment]
Implemented in version 0.1.3 ([b13b1ad1015fb41a9daa5afce3a0de883efcb21a](https://github.com/puresick/redirector/commit/b13b1ad1015fb41a9daa5afce3a0de883efcb21a))
